### ISSUE TITLE
Cloud Roadmap

### ISSUE THREAD

**Issue by danoro96** [RoboticMaterials/rmstudio#30]
What's done?

Basic Queries:
- [x] Stations
- [x] Tasks
- [x] Positions
- [x] Processes
- [x] Cards
- [x] Dashboards
- [x] Objects
- [x] Settings
- [x] Templates
- [x] CardHistories (I made this but needs the front end to change to match the new data structure)

Not sure about these:
- [x] SiteMaps (This only has gets. Need to create lambda functions for this)
- [ ] Schedules (not used anywhere?)
- [x] Events (not used anywhere?)

Data Stream:
- [x] TaskQueue

Analytics:
- [x] TaskAnalytics
- [x] StationStats
- [x] ReportsStats

Devices:
- [ ] Sounds
- [ ] Devices
- [ ] Status
